### ISSUE TITLE
SVG fails

### ISSUE THREAD

**Issue by corysimmons** [AwesomeStickz/verify-image-url#1]
I'd expect something like this to pass: https://upload.wikimedia.org/wikipedia/commons/e/ed/Logo_of_Unsplash.svg

**Comment by corysimmons** [comment]
At the bottom of the `image-type` README:

>SVG isn't included as it requires the whole file to be read, but you can get it [here](https://github.com/sindresorhus/is-svg).

Would you be open to adding https://npm.im/is-svg to this lib, or should I go ahead and patch for my use case?

Thanks for the cool lib!

**Comment by AwesomeStickz** [comment]
Good catch and thanks for the suggestion, I'll fix this soon!

**Comment by AwesomeStickz** [comment]
Added this in [`v1.3.0`](https://www.npmjs.com/package/verify-image-url/v/1.3.0). It's toggleable with the option `options.allowSVG`, as not everyone would want to treat SVGs as images I'd assume, at least not me with my use case.

**Comment by corysimmons** [comment]
Awesome! Thank you so much for the quick update! Your library is very helpful to me! <3

**Comment by 1803200** [comment]
$ npm i verify-image-url
